apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- perses-operator-deployment.yaml
- perses-operator-cluster-role.yaml
- perses-operator-service-account.yaml
- perses-operator-cluster-role-binding.yaml
